[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log

[program:fastapi]
command=/root/.local/bin/uvicorn api.main:app --host 0.0.0.0 --port 7860
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:dashboard]
command=/root/.local/bin/gunicorn dashboard.app:server -b 0.0.0.0:8050
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0